Repository Felix-44/Xilef, pull requests merged in 2021-12, with the labels that each got.

#55 add &brainfuck minigame
  src/Minigames/brainfuck.js
  src/commands.js
  src/economy.js
  src/minigames.js
Labels: enhancement

#58 new Matrix class
  src/Minigames/connect 4.js
  src/Minigames/minesweeper.js
  src/Minigames/reversi.js
  src/matrix.js
Labels: update

#21 Dungeons enemies thingy not done yet
  src/Minigames/dungeon.js
Labels: enhancement, balance issue

#68 add &lua command
  .gitignore
  src/commands.js
Labels: enhancement

#65 add &clash minigame
  src/Minigames/clash.js
  src/Pictures/Clash/barracks.png
  src/Pictures/Clash/beta barracks.png
  src/Pictures/Clash/beta cannon.png
  src/Pictures/Clash/beta dogecoin mine.png
  src/Pictures/Clash/beta town hall.png
  src/Pictures/Clash/cannon.png
  src/Pictures/Clash/crossbow.png
  src/Pictures/Clash/mine.png
  src/Pictures/Clash/town hall.png
  src/commands.js
  src/economy.js
  src/index.js
  src/matrix.js
  src/minigames.js
Labels: enhancement
